title: Tan Wei Jin
email: weijin96@hotmail.com
description: Personal portfolio, professional experience and writing by Tan Wei Jin.
baseurl: ""
url: "https://tanweij.in"
github_username: jinbean

theme: minima
plugins:
  - jekyll-feed

exclude:
  - _content/
  - scripts/
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
